name: ci

on: [push, pull_request] # 当有新 push 时触发

jobs:
  build: # 一项叫做 build 的任务
    runs-on: ubuntu-latest # 在最新版的 Ubuntu 系统下运行

    steps:
      - name: Clone repository # 将仓库内 master 分支的内容下载到工作目录
        uses: actions/checkout@v2 # 脚本来自 https://github.com/actions/checkout

      - name: run node # 配置 Node 环境
        uses: actions/setup-node@v2 # 配置脚本来自 https://github.com/actions/setup-node
        with:
          node-version: '14'

      - run: npm install
      - run: npm run test

      - name: Release
        uses: softprops/action-gh-release@v1
        if: |
          startsWith(github.repository, 'wlswang') && 
          startsWith(github.ref, 'refs/tags/')
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          draft: true
