name: schedule

on:
  schedule:
    - cron: '0/5 * * * *' # 定时执行11

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      TZ: Asia/Shanghai

    steps:
      - name: Clone repository
        uses: actions/checkout@v2

      - name: run node
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - run: npm install

      - run: echo "${{ github.actor }}" ${{ github.actor }}

      - run: echo "${{ secrets.SECRET_KEY }}" ${{ secrets.SECRET_KEY }}

      - run: echo "${{ github.repository }}" ${{ github.repository }}

      - name: code
        run: |
          git config --local user.email "bot@github.com"
          git config --local user.name "bot"           
          git remote set-url origin https://${{ github.actor }}:${{ secrets.SECRET_KEY }}@github.com/${{ github.repository }}
          git pull origin master
          node index.js
          git add .
          git commit -m "update by github action"
          git push origin master
          
          
