name: schedule

on: [push, pull_request] # 当有新 push 时触发


jobs:
  build:
    runs-on: ubuntu-latest

    env:
      TZ: Asia/Shanghai

    steps:
    

        
      - name: code1
        run: |
          git clone https://${{ secrets.SECRET_KEY }}@github.com/wlswang/toutiao-trending-hout-search.git
         

          
      - name: run node
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - run: npm install

      - name: code
        run: |
          # git config --local user.email "121840415@qq.com"
          # git config --local user.name "wlswang"  
          # git remote set-url origin https://${{ secrets.SECRET_KEY }}@github.com/wlswang/toutiao-trending-hout-search.git
          # git config --local  --list
          git pull origin master
          node index.js
          git add .
          git commit -m "update by github action"
          
          git push
          
          
